apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratingsapi
spec:
  selector:
    matchLabels:
      app: ratingsapi
  template:
    metadata:
      labels:
        app: ratingsapi # the label for the pods and the deployments
    spec:
      containers:
      - name: ratingsapi
        image: jyecontainerregistry.azurecr.io/ratingsapi # IMPORTANT: update with your own repository
        imagePullPolicy: Always
        ports:
        - containerPort: 3000 # the application listens to this port
        readinessProbe: # is the container ready to receive traffic?
          httpGet:
            port: 3000
            path: /healthz
        livenessProbe: # is the container healthy?
          httpGet:
            port: 3000
            path: /healthz
