apiVersion: apps/v1
kind: Deployment
metadata:
	name: ratingsapi
spec:
	selector:
		matchLabels:
			app: ratingsapi
	template:
		metadata:
			labels:
				app: ratingsapi # the label for the pods and the deployments
		spec:
			containers:
			- name: ratingsapi
				image: jyecontainerregistry.azurecr.io/ratingsapi
				imagePullPolicy: Always
				ports:
				- containerPort: 80                          
				resources:
					requests: # minimum resources required
						cpu: 250m
						memory: 64Mi
					limits: # maximum resources allocated
						cpu: 500m
						memory: 256Mi
				readinessProbe: # is the container ready to receive traffic?
					httpGet:
						port: 3000
						path: /health
				livenessProbe: # is the container healthy?
					httpGet:
						port: 3000
						path: /healthz
